### PR TITLE
Use `0.0.0.0` for setMulticastInterface

### PR DESCRIPTION
**Pull request by RangerMauve**
As discussed on IRC, this change should make it listen on "all interfaces" and should help with multi-interface scenarios not working.

### CODE REVIEW

**Comment by mafintosh** [comment]
Testing this now

**Comment by RangerMauve** [comment]
I don't have Linux installed anywhere at the moment. 😅

It worked on the Macbook I was using last week, as in, it was getting it's own MDNS packets.

I'll check on my Windows box later today.

Also, I think we need an `if` statement in there for IPv6 to default to the `::` which is the equivalent to `0.0.0.0`

**Comment by mafintosh** [comment]
Does it work on mac with wifi disabled?

**Comment by RangerMauve** [comment]
I _think_ so. 😕

Now I'm not 100% sure if I checked out the correct branch. 

I can check it out when I check on Windows today.

**Comment by RangerMauve** [comment]
Works on Windows 10 with the wifi turned off (I still have my VirtualBox network, though).

I'll try Mac in a bit.

**Comment by RangerMauve** [comment]
Just tested it out on Mac with wifi disabled, example.js and cli.js work fine.

**Comment by RangerMauve** [comment]
No idea what's going on with the red stuff around the curly braces :S

**Comment by mafintosh** [comment]
Seems to work great! out in 7.0.1

**Pull request merged**
