### PR TITLE
Manually bind to all external IPv4 interfaces

### PR DESCRIPTION
**Pull request by watson**
This needs to be tested in a real environment before we merge it.

### CODE REVIEW

**Comment by bnielsen1965** [comment]
Are there any plans to merge this? I have a couple of systems with multiple interfaces and after much troubleshooting I discovered the multi-interface issue and started writing my own patch. Then I came across this pull request.

**Comment by mafintosh** [comment]
this wasn't working as expected the last time we tried it. we should try it again though @watson

**Comment by watson** [comment]
@mafintosh yes - maybe we'll have time in Amsterdam or on nodebo.at

**Comment by bnielsen1965** [comment]
To add another two cents... I was heading down the path of adding multi-interface support and with the multi-interface listening working the next issue is multi-interface queries. But I pulled back and went with the simple solution of adding the interface option to the socket bind because it was all getting overly complicated. So I would like to suggest the following if you implement multi-interface support:

- Leave interface selection at a higher level and accept an option for a single interface or an array of interfaces. Adding interface selection in multicast-dns is creating more complexity in the low level code and buries the selection process deep in the dependency stack. I started to think that it may be better to let the application/user select the appropriate interface(s).

- If multi-interface listening is supported then it should probably support multi-interface queries as well. After I added multi-interface listening the solution was still not acceptable because my queries were going out on the wrong interface. Although it will likely require multiple sockets it seems that listening on multiple interfaces should also provide for queries on those same interfaces. This gets complicated, and this is where my doubts started and I backed off.

Anyhow, that is my two cents. And btw, thanks for the pure Javascript solution.

**Comment by bnielsen1965** [comment]
I have implemented multiple interface binding and broadcasting in my fork. And I have tested on a laptop with a KVM virtual network, wired, and wifi, I've tested on a Raspberry Pi running Raspbian with both wired and wifi interfaces up, and I've tested on a Windows 8.1 laptop with wireless and a VMWare virtual network.

The code will accept a single interface defined in the options or an array of interfaces. I am searching for available interfaces at a higher level and passing those details on to multicast-dns. The addMembership seems to work fine with a single socket and multiple interfaces for listening but the broadcast on multiple interfaces required the use of multiple sockets.

Do you guys want to take a look at [the fork](https://github.com/bnielsen1965/multicast-dns) and let me know if I should put in a pull request or note any issues you see?

https://github.com/bnielsen1965/multicast-dns

**Comment by bnielsen1965** [comment]
Quick update, I made formatting changes to pass test.js tests and fixed a bug I missed.

**Comment by mafintosh** [comment]
We have multi interface support in master now.

**Pull request closed without merging**
