### PR TITLE
'networkInterface' event

### PR DESCRIPTION
**Pull request by richardschneider**
I'm doing a peer-2-peer app and want to discover other peers when a new `network interface` is discovered.  This PR emits a 'networkInterface' event.

Also, I found some weirdness on Windows when the laptop sleeps and then wakes up.  So a couple of socket calls are wrapped in a try/catch.

@mafintosh Again, thanks for this library!

### CODE REVIEW

**Comment by richardschneider** [comment]
@mafintosh any comment?

**Comment by diasdavid** [comment]
@richardschneider can you add tests for these changes?

**Comment by mafintosh** [comment]
@richardschneider sorry for the delay. this looks good to me. are the try catches and membership drops necessary?

**Comment by richardschneider** [comment]
> I found some weirdness on Windows when the laptop sleeps and then wakes up. So a couple of socket calls are wrapped in a try/catch.

**Comment by drahnieR** [comment]
I was just trying do a PR for try/catch on `socket.setMulticastInterface`. This will be something I want as well.
@mafintosh are we going to merge this or another PR is preferred?

**Comment by mafintosh** [comment]
@drahnieR are you seeing errors without the try/catch ?

**Comment by drahnieR** [comment]
@mafintosh yes, this is what i got. I'm using https://github.com/watson/bonjour btw
```
Error: setMulticastInterface EADDRNOTAVAIL
    at Socket.setMulticastInterface (dgram.js:800:11)
    at EventEmitter.that.update (/home/pi/.node_modules/node_modules/multicast-dns/index.js:142:12)
    at Socket.<anonymous> (/home/pi/.node_modules/node_modules/multicast-dns/index.js:55:12)
    at Socket.emit (events.js:215:7)
    at startListening (dgram.js:148:10)
    at dgram.js:328:7
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
```

**Review by alxhotel — APPROVED** [review]

**Comment by alxhotel** [comment]
Hey @mafintosh, can you merge this. I think the try-catch will help.

**Comment by DiegoRBaquero** [comment]
@mafintosh can we get maintainer access for this package as well, similarly to chromecasts?

**Comment by mafintosh** [comment]
Thanks for the patience (and ping @alxhotel). Releasing now

**Comment by mafintosh** [comment]
7.2.4

**Comment by alxhotel** [comment]
Thanks @mafintosh ! :smile:

**Pull request merged**
